"""Twist-conditioned OMNIDIRECTIONAL crawl gait-library tracking, with blended clip transitions.

Same machinery as ``G1-Crawling-Fwd-Blending`` (twist-indexed gait library, reference-free actor,
idle-pose stop, and blended mid-episode clip transitions), but pointed at the FULL 3-D twist
library: the commanded twist ``[vx, vy, wz]`` varies on all three axes (forward, lateral, and
yaw-rate), so the policy learns forward crawling with lateral and turning steering from one command
space -- instead of the forward-only vx sweep of ``G1-Crawling-Fwd``.

The gait library is generated by mj-nlp's ``g1_gait_library.py`` (family ``crawl_fwd``: a 5x5x5
[vx, vy, wz] product grid) and converted to tracking npz by ``scripts/library_to_npz.py`` (which
also tiles ``qpos_idle.csv`` into a zero-twist stop clip). See ``config/g1/env_cfgs.py``.
"""
